### ISSUE TITLE
MixedReality-WebRTC 2.0.2 的 answer 始终返回 a=recvonly

### ISSUE THREAD

**Issue by malegend** [fallingrust/CameraRTMP#2]
你好！关于这个问题，您这边除了降低到1.03之外，还有什么好的解决办法啊？

[https://github.com/microsoft/MixedReality-WebRTC/issues/776
**answer always a=recvonly**](https://github.com/microsoft/MixedReality-WebRTC/issues/776)

**Comment by fallingrust** [comment]
emmm...没有用这个库了，https://github.com/sipsorcery-org/sipsorcery  用的这个，然后自己做渲染
